# Generated by Django 3.2.8 on 2021-10-25 06:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_auth', '0002_auto_20211007_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True, verbose_name='Email')),
                ('is_email_confirmed', models.BooleanField(default=False, verbose_name='Email подтвержден')),
                ('email_confirmation_code', models.CharField(max_length=15, verbose_name='Код подтверждения email')),
                ('token', models.CharField(max_length=40, verbose_name='Токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Код подтверждения по смс',
                'verbose_name_plural': 'Коды подтверждения по смс',
            },
        ),
        migrations.CreateModel(
            name='PhoneConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, unique=True, verbose_name='Телефон')),
                ('is_phone_confirmed', models.BooleanField(default=False, verbose_name='Номер телефона подтвержден')),
                ('phone_confirmation_code', models.CharField(max_length=15, verbose_name='Код подтверждения номера телефона')),
                ('token', models.CharField(max_length=40, verbose_name='Токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Код подтверждения по смс',
                'verbose_name_plural': 'Коды подтверждения по смс',
            },
        ),
    ]
