# Generated by Django 3.2.8 on 2021-10-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_auth', '0003_emailconfirm_phoneconfirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirm',
            name='email_confirmation_code',
            field=models.CharField(max_length=255, verbose_name='Код подтверждения email'),
        ),
    ]
