# Generated by Django 3.2.8 on 2021-10-27 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_auth', '0004_alter_emailconfirm_email_confirmation_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailconfirm',
            options={'verbose_name': 'Код подтверждения по email', 'verbose_name_plural': 'Коды подтверждения по email'},
        ),
    ]
