# Generated by Django 3.2.8 on 2021-10-28 07:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_auth', '0005_alter_emailconfirm_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirm',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='phoneconfirm',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон'),
        ),
    ]
