# Generated by Django 3.2.8 on 2021-11-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_auth', '0006_auto_20211028_0731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfirm',
        ),
        migrations.DeleteModel(
            name='PhoneConfirm',
        ),
    ]
