# Generated by Django 3.2.8 on 2021-10-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='event',
            field=models.IntegerField(blank=True, choices=[(2021, 'Подтверждение номера телефона'), (2022, 'Подтверждение email')], null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='notifytemplate',
            name='event',
            field=models.IntegerField(blank=True, choices=[(2021, 'Подтверждение номера телефона'), (2022, 'Подтверждение email')], null=True, verbose_name='Событие'),
        ),
    ]
